version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql_container
    depends_on:
      - db
    profiles:
      - debug